alias ll='ls -l -h --time-style="+%Y-%m-%d %H:%M:%S" --color=auto'
alias l='ll'
alias la='ll -A'
alias ns='sudo netstat -tulpn'
alias c='clear'
alias psjava='ps -ef|grep java'
alias psnginx='ps -ef|grep nginx'
alias cdd='cd /home/q/www/qhotel*'
alias tf='tailf logs/catalina.out'
alias date='date +"%Y-%m-%d %H:%M:%S"'
